remote-theme: minimal-mistakes-jekyll
title: Fruitloopins
description: Fruitloopins
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
