name: "Fruitloopins"
description: "Fruitloopins' stuff"

title: "Fruitloopins"
subtitle: "When the fruit is loopin"

remote-theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"

include: ["_pages"]

author:
  name: "Fruitloopins"
  location: "Earth"

footer:
  links:
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/ey6ZvnwAJp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Fruitloopins"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
