name: "Fruitloopins"
description: "Fruitloopins"

remote-theme: "mmistakes/minimal-mistakes"

include: ["_pages", "_posts"]

footer:
  links:
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/ey6ZvnwAJp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Fruitloopins"
