name: Fruitloopins
description: Fruitloopins' stuff

title: Fruitloopins
subtitle: When the fruit is loopin

remote-theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon

include: ["_pages"]

author:
  name: Fruitloopins
  bio: idk
  location: Earth
