name: "Fruitloopins"
description: "Fruitloopins' stuff"

title: "Fruitloopins"
subtitle: "When the fruit is loopin"

remote-theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"

include: ["_pages", "_posts"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true

author:
  name: "Fruitloopins"
  location: "Earth"

footer:
  links:
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/ey6ZvnwAJp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Fruitloopins"
