name: "Fruitloopins"
description: "Fruitloopins"
title_separator: "::"

title: "Fruitloopins"
subtitle: "When the fruit is loopin"

remote-theme: "mmistakes/minimal-mistakes"

include: ["_pages", "_posts"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
